name = "goldprice-api"
main = "worker/index.ts"
compatibility_date = "2025-11-01"
workers_dev = true

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[observability]
enabled = true

[[routes]]
pattern = "goldpricing.laow1.xyz"
custom_domain = true